config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moneris/', include('moneris.urls')),
    path('sale/', include('sale.urls')),
]

moneris/urls.py
from django.urls import path
from . import views

app_name = 'moneris'

urlpatterns = [
    path('', views.moneris_list, name='moneris_list'),
    path('<int:pk>/', views.moneris_detail, name='moneris_detail'),
    path('new/', views.moneris_create, name='moneris_create'),
    path('update/<int:pk>/', views.moneris_create, name='moneris_update'),
    path('delete/<int:pk>/', views.moneris_delete, name='moneris_delete'),
    path('payment/validate', views.moneris_payment_validate, name='moneris_payment_validate'),


]

sale/urls.py
from django.urls import path

from . import views
app_name = 'sale'

urlpatterns = [
    path('', views.sale_order_list, name='sale_order_list'),
    path('new/', views.sale_order_create, name='sale_order_create'),

]

moneris/models.py
from django.db import models

# Create your models here.


class Moneris(models.Model):
    status = (
        ('test', 'Test'),
        ('prod', 'Prod')
    )
    name = models.CharField(max_length=100, unique=True)
    ps_store_id = models.CharField(max_length=100, null=False, blank=False)
    hpp_key = models.CharField(max_length=100, null=False, blank=False)
    access_token = models.CharField(max_length=100, null=True, blank=True)
    api_username = models.CharField(max_length=100, null=True, blank=True)
    api_password = models.CharField(max_length=100, null=True, blank=True)
    environment = models.CharField(max_length=10, choices=status, default='test')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def _get_moneris_urls(self, environment):
        """ Moneris URLS """
        if environment == 'prod':
            return {
                'moneris_form_url': 'https://www3.moneris.com/HPPDP/index.php',
                'moneris_auth_url': 'https://www3.moneris.com/HPPDP/verifyTxn.php',
            }
        else:
            return {
                'moneris_form_url': 'https://esqa.moneris.com/HPPDP/index.php',
                'moneris_auth_url': 'https://esqa.moneris.com/HPPDP/verifyTxn.php',
            }

sale/models.py
from django.db import models

from moneris.models import Moneris


class SaleOrder(models.Model):
    status = (
        ('draft', 'Draft'),
        ('paid', 'Paid'),
        ('cancelled', 'Cancel')
    )
    sale_order = models.AutoField(primary_key=True)
    payment = models.CharField(choices=status,default='draft', null=False, blank=False, max_length=111)
    payment_acquire = models.ForeignKey(Moneris, related_name='payment_by', on_delete=models.SET_NULL,null=True)
    price = models.FloatField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

moneris/forms.py
from .models import Moneris
from django import forms


class MonerisForm(forms.ModelForm):

    class Meta:
        model = Moneris
        fields = ('name', 'ps_store_id', 'hpp_key', 'access_token', 'environment')

sale/forms.py
from django import forms

from .models import SaleOrder


class SaleOrderForm(forms.ModelForm):
    class Meta:
        model = SaleOrder
        fields = ('payment_acquire', 'price')

moneris/views.py
from django.shortcuts import render,get_object_or_404, redirect

from .models import Moneris
from .forms import MonerisForm
from sale.models import SaleOrder
import requests
import pdb
from django.views.decorators.csrf import csrf_exempt

def moneris_list(request):
    object_list = Moneris.objects.all()
    return render(request, 'moneris/moneris_list.html', {'object_list': object_list})


def moneris_detail(request, pk):
    object = get_object_or_404(Moneris, pk=pk)
    return render(request, 'moneris/moneris_detail.html', {'object': object})


def moneris_create(request, **kwargs):
    pk = kwargs.get('pk')
    if pk:
        object = get_object_or_404(Moneris, pk=pk)
        form = MonerisForm(instance=object, data=request.POST or None)
    else:
        form = MonerisForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect("moneris:moneris_list")
    return render(request, 'moneris/moneris_create.html', {'form': form})


def moneris_delete(request, pk):
    object = get_object_or_404(Moneris, pk=pk)
    object.delete()
    return redirect('moneris:moneris_list')

@csrf_exempt
def moneris_payment_validate(request):
    kwargs = request.POST
    if request.method == 'POST':
        order_id = kwargs.get('response_order_id')
        sale_order_obj = SaleOrder.objects.get(sale_order=int(order_id))
        if sale_order_obj:
            url = sale_order_obj.payment_acquire._get_moneris_urls(sale_order_obj.status)['moneris_auth_url']
            info = {
                'ps_store_id': sale_order_obj.payment_acquire.ps_store_id,
                'hpp_key': sale_order_obj.payment_acquire.hpp_key,
                'charge_total': sale_order_obj.price,
                'order_id': sale_order_obj.sale_order,
                'validate_url': url
            }
            new_post = dict(ps_store_id=info['ps_store_id'], hpp_key=info['hpp_key'], transactionKey=kwargs.get('transactionKey'))
            r = requests.post(url=info['validate_url'], data=new_post)
            resp = r.text


            part = resp.split('<br>')
            new_response = dict([s.split(' = ') for s in part])

            success = kwargs.get('response_code')

            try:
                if (int(success) < 50 and kwargs.get('result') == '1' and
                        new_response.get('response_code') is not 'null' and int(new_response.get('response_code')) < 50 and
                        new_response.get('status') == 'Valid-Approved' and
                        new_response.get('amount') is not 'null' and float(new_response.get('amount')) == float(
                            kwargs.get('charge_total')) and
                        new_response.get('transactionKey') == kwargs.get('transactionKey') and
                        new_response.get('order_id') == kwargs.get('response_order_id')
                ):

                    sale_order_obj.payment = 'paid'
                    sale_order_obj.payment = 'cancelled'
            except ValueError:
                sale_order_obj.payment = 'cancelled'
            #pdb.set_trace()
            sale_order_obj.save()

        return redirect("sale:sale_order_list")

sale/views.py
from django.shortcuts import render, redirect
import requests
# Create your views here.
from .models import SaleOrder
from .forms import SaleOrderForm

import pdb


def sale_order_list(request):
    sol = SaleOrder.objects.all()
    return render(request, 'sale/sale_order_list.html', {'object_list':sol})


def sale_order_create(request):
    form = SaleOrderForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            soo = form.save()
            if soo.sale_order:
                url = soo.payment_acquire._get_moneris_urls(soo.status)['moneris_form_url']
                form = {
                   'ps_store_id': soo.payment_acquire.ps_store_id,
                   'hpp_key': soo.payment_acquire.hpp_key,
                   'charge_total': soo.price,
                   'order_id': soo.sale_order,
                    'url': url
               }
                return render(request, 'sale/payment.html', {'form': form})

    return render(request, 'sale/sale_order_create.html', {'form':form})

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/static.css' %}">
    <title>{% block title%}Moneris{% endblock %}</title>
  </head>
  <body>
    <div id="content" class="container">
        {% block content  %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/moneris/moneris_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update</h1>
   <form method="POST" >{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

{% endblock %}

templates/moneris/moneris_detail.html
{% extends 'base.html' %}
{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">ps_store_id</th>
                <th scope="col">hpp_key</th>
                <th scope="col">access_token</th>
            </tr>
        </thead>
         <tbody>
            <tr>

              <td>{{object.name}}</td>
              <td>{{object.ps_store_id}}</td>
              <td>{{object.hpp_key}}</td>
               <td>{{object.access_token}}</td>
            </tr>
         </tbody>
    </table>
    <a href="{% url 'moneris:moneris_update' object.pk %}" type="button" class="btn btn-primary">Update</a>
    <a href="{% url 'moneris:moneris_delete' object.pk %}" type="button" class="btn btn-danger">Delete</a>
{% endblock %}

templates/moneris/moneris_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Moneris List</h1>
    <div class="float-right">
        <h1>New</h1>
        <a href="{% url 'moneris:moneris_create' %}" >Create new store</a>
    </div>

    <ol>
        {% for object in object_list %}
            <li><a href="{% url 'moneris:moneris_detail' pk=object.id %}">{{object.name}}</a></li>
        {% endfor %}
    </ol>

{% endblock %}

templates/sale/payment.html
{% extends 'base.html' %}
{% block content %}
    <h1>Make payment</h1>
    <h2>Pay with Moneris</h2>
    <form method="POST" action="{{form.url}}">{% csrf_token %}
        <input type="hidden" name="ps_store_id" value="{{form.ps_store_id}}"/>
        <input type="hidden" name="hpp_key" value="{{form.hpp_key}}"/>
        <input type="hidden" name="charge_total" value="{{form.charge_total}}"/>
         <input type="hidden" name="order_id" value="{{form.order_id}}"/>
        <button type="submit" class="btn btn-primary">Pay</button>
    </form>
{% endblock %}

templates/sale/sale_order_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Sale Order</h1>
    <form method="POST" >{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/sale/sale_order_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sale Order List</h1>
    <div class="float-right">
        <h1>New</h1>
        <a href="{% url 'sale:sale_order_create' %}" >Create new sale order</a>
    </div>
 <table class="table">
        <thead>
            <tr>
                <th scope="col">sale_order</th>
                <th scope="col">payment_acquire</th>
                <th scope="col">payment</th>
                <th scope="col">price</th>
            </tr>
        </thead>
         <tbody>
         {% for object in object_list %}
            <tr>

              <td>{{object.sale_order}}</td>
              <td>{{object.payment_acquire}}</td>
              <td>{{object.payment}}</td>
                <td>{{object.price}}</td>
            </tr>
         {% endfor %}
         </tbody>
    </table>

{% endblock %}